default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  database: hotel_management_development

test:
  <<: *default
  database: hotel_management_test

production:
  <<: *default
  database: hotel_management_production
  username: hotel_management
  password: <%= ENV['HOTEL_MANAGEMENT_DATABASE_PASSWORD'] %>
